### ISSUE TITLE
Problem with executeTrade

### ISSUE THREAD

**Issue by frankiminternet** [peshay/btcde#28]
Hi, 
thank for creating this library.
I found an issue with executeTrade()
A normal trade execution works perfectly.
But a python error will be raised if there is a problem like 'order id does not exist' or 'order not possible'.
The reason is that the API also responds with http status codes 403, 404, 422
I have added these codes to HandleAPIErrors(), this works for me.
But i  am not sure if this is the correct solution.
Frank

**Comment by peshay** [comment]
No, the status codes in that method are if there is NO error and then it‘s tested if the error code is NOT one of them, so in that case the actual error message will be extracted and shown.
Could it be that your issue is related to #12 ?
This will then be fixed in 2.2

**Comment by frankiminternet** [comment]
Hi, thank you, 
Yes, it is the same problem as in #12
I am waiting for 2.2
Best Regards ,
Frank 


Send mobile
