### ISSUE TITLE
Please help me to understand the **args

### ISSUE THREAD

**Issue by dr-apple** [peshay/btcde#34]
Hello, can you give me same example for the **args ?

showOrderbook(OrderType, trading_pair, **args)

how i had to write only_express_orders in a **args ?

Please more samples :-)

**Comment by peshay** [comment]
It’s the optional parameters. For example:

conn = btcde.Connection(api_key, api_secret)
orderbook = conn.showOrderbook('buy', 'btceur', amount=„3“, price=„8000“)

**Comment by dr-apple** [comment]
sorry, but i don't understand the example ?

for what is  amount=„3“ and price=„8000“ ?

**Comment by peshay** [comment]
Like I said, some of the optional parameters for that function as they are described in the readme.
