### ISSUE TITLE
Delete und andere Order Requests funktionieren nicht

### ISSUE THREAD

**Issue by wwender** [peshay/btcde#5]
Hallo Zusammen,

damit werden schon einige Probleme gehabt haben aber trotz diskussion im Forum hat wohl keine hier was zum Code geändert. Die Parameter mit dem ":" sind so nicht richtig angegeben.

Bei delete sollte das richtig so aussehen:

def deleteOrder(conn, order_id):
    """Delete an Order."""
    #newuri = orderuri + ":" + order_id  KEIN DOPPELPUNKT ABER SLASH
    newuri = orderuri + "/" + order_id
    params = {'order_id': order_id}
    return APIConnect(conn, 'DELETE', params, newuri)

Bei my order Details so:
def showMyOrderDetails(conn, order_id):
    """Details to an own Order."""
    #newuri = orderuri + '/:' + order_id  KEIN DOPPELPUNKT!
    newuri = orderuri + '/' + order_id
    params = {'order_id': order_id}
    return APIConnect(conn, 'GET', params, newuri)

=> Die anderen calls müsste man dann paralell ändern. Bei den beiden kann ich es aber mit Sicherheit bestätigen, da ich die so getestet haben.
Viele Grüße und Danke für die Sourcen :)

**Comment by peshay** [comment]
Kannst du das als Pull Request machen?

**Comment by wwender** [comment]
Gerne :)
