### ISSUE TITLE
tradingpair xrpeur

### ISSUE THREAD

**Issue by marionet** [peshay/btcde#56]
How can the tradingpair xrpeur be added?

**Comment by CosmicDuck** [comment]
Simply add xrp and xrpeur to the existing values?

`

…
    TRADING_PAIRS = ['btceur', 'bcheur', 'etheur', 'btgeur', 'bsveur', 'ltceur',
                     **'xrpeur',** 'iotabtc', 'dashbtc', 'gntbtc', 'ltcbtc']
    ORDER_TYPES = ['buy', 'sell']
    CURRENCIES = ['btc', 'bch', 'eth', 'btg', 'bsv', 'ltc',
                  'iota', 'dash', 'gnt'**, 'xrp'**]
…
`

**Comment by peshay** [comment]
Can you create a PR for it, with a unit test and documentation about that function in the README?

**Comment by CosmicDuck** [comment]
Hello,

I see there is already an existing pull request which contains integration of xrp and doge in #58 additionally to ssl-verify warning pr. So I will not add more work for these issue.

**Comment by cj4c0b1** [comment]
it's done on #59 
we can close this.
