### ISSUE TITLE
Not working with python 2.7 because of http.client

### ISSUE THREAD

**Issue by gitoops** [peshay/btcde#7]
Hi,
the code in btcede.py line 17,18 need to differ between python 2.7 and 3.
Doc of httplib says "The httplib module has been renamed to http.client in Python 3".
In case of  version < 3 the lib is called httplib else http.client
Rgds
jammcc

**Comment by peshay** [comment]
b17885c49186e9e5ff9ef6df851d3d3313a76ff3 I added "future" to the requirements, so it will work with python2 as well 
http://python-future.org/compatible_idioms.html#http-module
